Add a new protection, MessageIsMedia
matrix-org/mjolnir pull request #108
Opened 2021-06-28 10:01 UTC by chirayudesai

* Simply redacts any media sent to the room, by anyone
* Meant to serve as a temporary measure to prevent gore image spam,
  in conjunction with FirstMessageIsImage

TODOs:
* Add more fine grained handling, like
  * Only redact media from new users
  * Allow moderating / allowing media
  * Run it by some sort of filter
  * Filename filter
  * Hostname / username filter

Endless possiblities, but this should do for now.
If the clients could totally disable media preview that would work too.

2021-06-28 10:02 UTC, chirayudesai commented
We've been getting a lot of gore image spam on our channels over the weekend.

I did this as a temporary measure while something is figured out. To cover anything that FirstMessageIsImage doesn't cover for now.

2021-06-28 10:30 UTC, chirayudesai commented
Docker image with this commit: registry.gitlab.com/cde/mjolnir:latest

2021-09-13 17:13 UTC, chirayudesai commented
If you're using https://github.com/spantaleev/matrix-docker-ansible-deploy , it can also be used like:

```
matrix_bot_mjolnir_container_image_self_build: true
matrix_bot_mjolnir_container_image_self_build_repo: "https://github.com/chirayudesai/mjolnir"
```

2021-09-24 07:09 UTC, Yoric commented
@Gnuxie Could you review this?

2021-09-24 11:06 UTC, Gnuxie requested changes
@chirayudesai This works great, thank you! If you could add the missing space we will be able to merge this

@Yoric I have tested it with my ongoing refactor and there are no issues.

2021-09-24 11:27 UTC, chirayudesai commented on src/protections/protections.ts
> +        factory:() => new MessageIsMedia(),
Done.

2021-09-24 13:58 UTC, Gnuxie approved these changes
Great, thank you!

2021-09-24 13:59 UTC, merged